"""CDP connection tests — property-based roundtrip verification.

Tests that packets generated by make_packet can be correctly parsed
by parse_packet, confirming the protocol layer contract.
"""
from __future__ import annotations

import struct

from hypothesis import given, settings
from hypothesis import strategies as st

from megaphone.protocol import (
    MSG_MEGAPHONE,
    make_packet,
    parse_megaphone,
    parse_packet,
)

from conftest import megaphone_text, packet_type, valid_packet


class TestCDPRoundtrip:
    """Property-based CDP protocol roundtrip tests."""

    @given(pkt=valid_packet())
    @settings(max_examples=100)
    def test_roundtrip(self, pkt: tuple):
        """INVARIANT: make → parse roundtrip preserves payload."""
        full_pkt, _, expected_mt, expected_pl = pkt
        _, msg_type, payload = parse_packet(full_pkt)
        assert msg_type == expected_mt
        assert payload == expected_pl

    @given(mt=packet_type(), pl=st.binary(max_size=100))
    @settings(max_examples=100)
    def test_all_packet_types_roundtrip(self, mt: int, pl: bytes):
        """INVARIANT: all packet types survive roundtrip."""
        _, msg_type, payload = parse_packet(make_packet(mt, pl))
        assert msg_type == mt
        assert payload == pl

    @given(text=megaphone_text())
    @settings(max_examples=100)
    def test_megaphone_text_roundtrip(self, text: str):
        """INVARIANT: megaphone text parsed from packet preserves sender + message."""
        text_bytes = text.encode("utf-8")
        # Layout: [8B junk][4B msg_id][4B meta][4B text_len][text]
        payload = (
            b"\x00" * 8
            + struct.pack(">III", 1, 0, len(text_bytes))
            + text_bytes
        )
        pkt = make_packet(MSG_MEGAPHONE, payload)
        _, mt, pl = parse_packet(pkt)
        assert mt == MSG_MEGAPHONE
        result = parse_megaphone(pl)
        assert result is not None
        reconstructed = f"{result['sender']} : {result['message']}"
        assert reconstructed == text
